[package]
name = "packery"
version = "0.1.0"
edition = "2024"

[features]
default = ["alloc"]
std = []
alloc = []

[dependencies]
pager = { path = "../pager" }

[dependencies.thiserror]
version = "2.0.12"
default-features = false
