[package]
name = "bootbridge"
version = "0.1.0"
edition = "2024"

[dependencies]
c_enum = { path = "../c_enum" }
santa = { path = "../santa"}

[dependencies.bakery]
path = "../bakery"
default-features = false
features = ["alloc"]

