[package]
name = "kernel_proc"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
syn = { version = "2.0.108", features = ["full", "extra-traits"]}
proc-macro2 = "1.0.103"
convert_case = "0.8.0"
